
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author v
 */
public class convert extends javax.swing.JFrame {

    /**
     * Creates new form convert
     */
    public convert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fromcurrency = new javax.swing.JComboBox<>();
        Tocurrency = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel = new javax.swing.JTextField();
        Output = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(242, 242, 242), null));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("From Currency Of");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 297, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("To Currency Of");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 262, -1));

        fromcurrency.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fromcurrency.setForeground(new java.awt.Color(102, 0, 102));
        fromcurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "USD(United States Dollar)", "INR(Indian Rupees)", "EURO(Euro)", "CAD(Canadian Dollar)", "JPY(Japanese Yuan)", "CNY(Chinese Yen)", "BTC(Bitcoin)", " " }));
        fromcurrency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 1, 51), 3));
        jPanel1.add(fromcurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 248, 33));

        Tocurrency.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Tocurrency.setForeground(new java.awt.Color(102, 0, 102));
        Tocurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "USD(United States Dollar)", "INR(Indian Rupees)", "EURO(Euro)", "CAD(Canadian Dollar)", "JPY(Japanese Yuan)", "CNY(Chinese Yen)", "BTC(Bitcoin)" }));
        Tocurrency.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 1, 51), 3, true));
        jPanel1.add(Tocurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 225, 33));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Amount Of");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 210, -1));

        jLabel.setBackground(new java.awt.Color(242, 242, 242));
        jLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(204, 0, 0));
        jLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelKeyPressed(evt);
            }
        });
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 306, 37));

        Output.setBackground(new java.awt.Color(242, 242, 242));
        Output.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Output.setForeground(new java.awt.Color(204, 0, 51));
        Output.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 1, 51), 3, true));
        jPanel1.add(Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 400, 37));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("Units");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 110, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 102));
        jLabel6.setText("Units");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 110, 80));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("CONVERT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 140, 50));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 130, 47));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton2.setText("RESET");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 147, 47));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 308, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 0, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton4.setText("CURRENCY  CONVERTOR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\v\\Desktop\\images\\courrency1.jpeg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            jLabel.setEditable(false);
            
        }
        else{
            jLabel.setEditable(true);
        }
        
    }//GEN-LAST:event_jLabelKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel.setText(null);
        Output.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm you want to exit","EXIT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double total;
        Double amount= Double.parseDouble(jLabel.getText());
        switch(fromcurrency.getSelectedItem().toString()){
            case "USD(United States Dollar)":
                switch(Tocurrency.getSelectedItem().toString()){
                    
                    case "INR(Indian Rupees)":
                total =amount*82.743;
                Output.setText(jLabel.getText()+"  USD =  " +  total  + " RUPEES");
                break;
                    case "EURO(Euro)":
                total = amount*0.943;
                Output.setText(jLabel.getText()+" USD = " +total+"  EURO");
                break;
                    case "CAD(Canadian Dollar)":
                total = amount*1.351;
                Output.setText(jLabel.getText()+"  USD = " +total+"  DOLLAR");
                break;
                    case "JPY(Japanese Yuan)":
                total = amount*132.440;
                Output.setText(jLabel.getText()+"  USD = "  +total+"  YUAN");
                break;
                    case "CNY(Chinese Yen) ":
                total =amount*6.871;
                Output.setText(jLabel.getText()+"  USD = "+total+" YEN");
                break;
                     case"BTC(Bitcoin)":
                total =amount*0.0000594;
                Output.setText(jLabel.getText()+"  USD = "+total+" BITCOIN");
                break;
                     default:
                         total =amount*1;
                         Output.setText(jLabel.getText()+"  USD = "+total+" DOLLAR");
                
                }
                break;
            case "INR(Indian Rupees)":
                switch(Tocurrency.getSelectedItem().toString()){
                    case "USD(United States Dollar)":
                        total = amount*0.0120;
                        Output.setText(jLabel.getText()+" INR = "+total+"  USD");
                        break;
                    case "EURO(Euro)":
                        total = amount*0.01139;
                        Output.setText(jLabel.getText()+"  INR = "+total+"  EUR");
                        break; 
                    case "CAD(Canadian Dollar)":
                        total = amount*0.0163;
                        Output.setText(jLabel.getText()+"  INR = "+total+" CAD");
                        break;
                    case "JPY(Jpanese Yuan)":
                        total = amount*1.6012;
                        Output.setText(jLabel.getText()+"  INR = "+total+" JPY");
                        break; 
                    case "CNY(Chinese Yen)":
                        total = amount*0.083;
                        Output.setText(jLabel.getText()+" INR = "+total+" CNY");
                        break; 
                    case "BTC(Bitcoin)":
                        total = amount*0.000000726;
                        Output.setText(jLabel.getText()+" INR = "+total+"  BTC");
                        break; 
                    default:
                        total = amount*1;
                        Output.setText(jLabel.getText()+" INR = "+total+"  INR");
                        break;
                }
                break;
            case "EURO(Euro)":
                switch(Tocurrency.getSelectedItem().toString()){
                    case "USD(United States Dollar)":
                        total = amount*1.06057;
                        Output.setText(jLabel.getText()+"  EURO = "+total+"  USD");
                        break;
                    case "INR(Indian Rupees)":
                        total = amount*87.74738;
                        Output.setText(jLabel.getText()+" EUR = "+total+"  INR");
                        break; 
                    case "CAD(Canadian Dollar)":
                        total = amount*1.4336;
                        Output.setText(jLabel.getText()+" EUR = "+total+"  CAD");
                        break;
                    case "JPY(Japanese Yuan)":
                        total = amount*140.5083;
                        Output.setText(jLabel.getText()+" EUR = "+total+"  YUAN");
                        break;
                    case "CNY(Chinese Yen)":
                        total = amount*7.2625;
                        Output.setText(jLabel.getText()+"  EUR = "+total+"  YEN");
                        break;
                    case "BTC(Bitcoin)":
                        total = amount*0.0000630;
                        Output.setText(jLabel.getText()+" EUR = "+total+" BITCOIN");
                        break; 
                    default:
                        total = amount*1;
                        Output.setText(jLabel.getText()+"  EUR = "+total+"  EURO");
                        break;
                }
                break;
            case "CAD(Canadian Dollar)":
                switch(Tocurrency.getSelectedItem().toString()){
                    case "USD(United States Dollar)":
                        total = amount*0.7397;
                        Output.setText(jLabel.getText()+"  CAD = "+total+"  USD");
                        break;
                    case "INR(Indian Rupees)":
                        total = amount*61.2043;
                        Output.setText(jLabel.getText()+"  CAD = "+total+"  INR");
                        break;  
                    case "EUR":
                        total = amount*0.6975;
                        Output.setText(jLabel.getText()+"  CAD = "+total+"  EUR");
                        break;
                    case "JPY(Jpanese Yuan)":
                        total = amount*98.0054;
                        Output.setText(jLabel.getText()+"  CAD = "+total+" YUAN");
                        break;  
                    case "CNY(Chinese Yen)":
                        total = amount*5.0865;
                        Output.setText(jLabel.getText()+" CAD = "+total+"  YEN");
                        break;    
                    case "BTC(Bitcoin)":
                        total = amount*0.0000439;
                        Output.setText(jLabel.getText()+"  CAD = "+total+"  BITCOIN");
                        break; 
                    default:
                        total = amount*1;
                        Output.setText(jLabel.getText()+" CAD = "+total+" DOLLAR");
                        break;
                }
                break;
            case"JPY(Japanese Yuan)":
                switch(Tocurrency.getSelectedItem().toString()){
                    case "USD(United States Dollar)":
                        total = amount*0.00754;
                        Output.setText(jLabel.getText()+"  JPY = "+total+"  USD");
                        break;
                    case "INR(Indian Rupees)":
                        total = amount*0.6244;
                        Output.setText(jLabel.getText()+"  JPY = "+total+"  INR");
                        break;
                    case "EURO(Euro)":
                        total = amount*0.00711;
                        Output.setText(jLabel.getText()+" JPY = "+total+"   EURO");
                        break;
                    case "CAD(Canadian Dollar)":
                        total = amount*0.01020;
                        Output.setText(jLabel.getText()+"  JPY = "+total+"  DOLLAR");
                        break; 
                    case "CNY(Chinese Yen)":
                        total = amount*0.051900;
                        Output.setText(jLabel.getText()+"  JPY = "+total+"  USD");
                        break;
                    case "BTC(Bitcoin)":
                        total = amount*0.0000000453;
                        Output.setText(jLabel.getText()+"  JPY = "+total+"  BTC");
                        break;
                    default:
                        total = amount*1;
                        Output.setText(jLabel.getText()+"  JPY = "+total+"  JPY");
                        break;
                }
                break;
            case "CNY(Chinese Yen)":
                switch(Tocurrency.getSelectedItem().toString()){
                    case"USD(United States Dollar)":
                        total =amount*0.1454;
                        Output.setText(jLabel.getText()+"  CNY = "+total+"  DOLLAR");
                        break;
                    case"INR(Indian Rupees)":
                        total =amount*12.0325;
                        Output.setText(jLabel.getText()+" CNY = "+total+"  RUPEES");
                        break;
                    case"EURO(Euro)":
                        total =amount*0.13712;
                        Output.setText(jLabel.getText()+" CNY = "+total+"  EURO");
                        break;
                    case"CAD(Canadian Dollar)":
                        total =amount*0.19659;
                        Output.setText(jLabel.getText()+" CNY = "+total+" DOLLAR");
                        break;
                    case"JPY(Japanese Yuan)":
                        total =amount*19.26750;
                        Output.setText(jLabel.getText()+"  CNY = "+total+"  YUAN");
                        break;
                    case"BTC(Bitcoin)":
                        total =amount*0.000008646;
                        Output.setText(jLabel.getText()+"  CNY = "+total+"  BITCOIN");
                        break;
                     default:
                        total = amount*1;
                        Output.setText(jLabel.getText()+"CNY="+total+"CNY");
                        break;  
            }
                break;
            case "BTC(Bitcoin)":
                switch(Tocurrency.getSelectedItem().toString()){
                    case "USD(United States Dollar)":
                        total = amount*16820.845;
                        Output.setText(jLabel.getText()+"  BTC =  "+total+"   DOLLAR");
                        break;
                    case "INR(Indian Rupees)":
                        total = amount*1391685.7254;
                        Output.setText(jLabel.getText()+"  BTC =  "+total+"  RUPEES");
                        break;
                     case "EURO(Euro)":
                        total = amount*15860.1393;
                        Output.setText(jLabel.getText()+" BTC = "+total+"  EURO");
                        break;
                     case "CAD(Canadian Dollar":
                        total = amount*22738.3511;
                        Output.setText(jLabel.getText()+"  BTC = "+total+"  DOLLAR");
                        break;
                      case "JPY(Japanese Yuan)":
                        total = amount*2228482.3907;
                        Output.setText(jLabel.getText()+"  BTC = "+total+"  YUAN");
                        break;  
                      case "CNY(Chinese Yen)":
                        total = amount*115660.1311;
                        Output.setText(jLabel.getText()+"  BTC = "+total+"  YEN");
                        break;
                     default:
                        total = amount*1;
                        Output.setText(jLabel.getText()+"  BTC = "+total+"  BITCOIN");
                        break;
                         
                }
                break;
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Output;
    private javax.swing.JComboBox<String> Tocurrency;
    private javax.swing.JComboBox<String> fromcurrency;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
